export * from './functions/clickWidgetByName'
export * from './functions/clickWidgetByNameAt'
export * from './functions/getWidgetPropByName'
export * from './functions/getWidgetPropByNameAt'
export * from './functions/setWidgetPropByName'
export * from './functions/setWidgetPropByNameAt'
export * from './functions/testWidgetPropByName'
export * from './functions/testWidgetPropByNameAt'